### ISSUE TITLE
怎么修改行高和行宽

### ISSUE THREAD

**Issue by baiRookie** [woshixiaoniqiu/wechat-table#1]
如题，求助

**Comment by jackieliu007** [comment]
wechat-table@v1.0.7中新增了属性可供使用者自定义设置表格样式：
1. 新增headOption.thStickyStyle和headOption.thStyle属性，用于设置表头单元格样式
2. 新增bodyOption.tdStickyStyle和bodyOption.tdStyle属性，用于设置表格body单元格的样式

npm包地址：https://www.npmjs.com/package/wechat-table/v/1.0.7
