### ISSUE TITLE
引入出现问题

### ISSUE THREAD

**Issue by congcong998** [woshixiaoniqiu/wechat-table#2]
![image](https://user-images.githubusercontent.com/68733345/119639485-3d493f80-be4a-11eb-9e13-f68cec7b3e6d.png)

**Comment by jackieliu007** [comment]
感谢提出，经排查发现源码中的bodyOptiton配置拼写错误，是作者不严谨了。
据问题图片推断应该是此原因导致未生成富文本html，已在wechat-tahble@1.0.7版本修复。
