### ISSUE TITLE
为什么颜色样式不生效，用的你的demo

### ISSUE THREAD

**Issue by fakeryu** [woshixiaoniqiu/wechat-table#3]
![image](https://user-images.githubusercontent.com/8454472/138830279-813db914-d4ed-42a8-8c05-8d4583e7c01c.png)

**Comment by jackieliu007** [comment]
wechat-table组件库1.0.8版本已修复，下载1.0.8版本后重新构建npm，再试试呢

**Comment by fakeryu** [comment]
行了，大兄弟
